from __future__ import annotations

from pathlib import Path
from typing import Any

import numpy as np
import pandas as pd


def _maybe_scalar(v: Any) -> Any:
    if isinstance(v, np.ndarray) and v.ndim == 0:
        return v.item()
    return v


def _decode_ts_ns(v: Any) -> pd.DatetimeIndex:
    arr = np.asarray(v)
    if arr.size == 0:
        return pd.DatetimeIndex([], tz="UTC")
    return pd.to_datetime(arr.astype("int64"), utc=True)


def load_npy_meta(path: str | Path, decode_datetime: bool = True) -> dict[str, Any]:
    """
    Load .npy metadata generated by utils.persist.save_npy_payload.

    By convention, keys ending with `_ts_ns` are decoded to UTC DatetimeIndex.
    """
    raw = np.load(str(path), allow_pickle=True).item()
    out: dict[str, Any] = {}
    for k, v in raw.items():
        vv = _maybe_scalar(v)
        if decode_datetime and k.endswith("_ts_ns"):
            out[k] = _decode_ts_ns(vv)
        else:
            out[k] = vv
    return out


def meta_to_dataframe(meta: dict[str, Any]) -> pd.DataFrame:
    """
    Convert loaded meta payload to a convenient DataFrame view.

    Supported kinds:
    - forecast_layer
    - return_target_layer
    - backtest_layer
    """
    kind = str(meta.get("kind", ""))

    if kind == "forecast_layer":
        idx = meta.get("target_ts_ns", pd.DatetimeIndex([]))
        return pd.DataFrame(
            {
                "close_gt_t1": np.asarray(meta.get("close_gt_t1", []), dtype=float),
                "pred_price_t1": np.asarray(meta.get("pred_price_t1", []), dtype=float),
                "band_lo_t1": np.asarray(meta.get("band_lo_t1", []), dtype=float),
                "band_hi_t1": np.asarray(meta.get("band_hi_t1", []), dtype=float),
            },
            index=pd.DatetimeIndex(idx),
        )

    if kind == "return_target_layer":
        idx = meta.get("target_ts_ns", pd.DatetimeIndex([]))
        return pd.DataFrame(
            {
                "pred_next_return": np.asarray(meta.get("pred_next_return", []), dtype=float),
                "real_next_return": np.asarray(meta.get("real_next_return", []), dtype=float),
                "band_lo": np.asarray(meta.get("band_lo", []), dtype=float),
                "band_hi": np.asarray(meta.get("band_hi", []), dtype=float),
            },
            index=pd.DatetimeIndex(idx),
        )

    if kind == "backtest_layer":
        idx = meta.get("settle_ts_ns", pd.DatetimeIndex([]))
        df = pd.DataFrame(index=pd.DatetimeIndex(idx))
        for col in ("pos", "dpos", "pnl", "equity_settle"):
            if col in meta:
                arr = np.asarray(meta[col], dtype=float)
                if len(arr) == len(df.index):
                    df[col] = arr
        return df

    raise ValueError(f"Unsupported meta kind: {kind}")


if __name__ == "__main__":
    import argparse

    p = argparse.ArgumentParser(description="Load and preview exp_results_meta .npy payloads")
    p.add_argument("path", help="Path to .npy meta file")
    p.add_argument("--head", type=int, default=5, help="Rows to print for DataFrame preview")
    args = p.parse_args()

    meta = load_npy_meta(args.path, decode_datetime=True)
    print("kind:", meta.get("kind"))
    print("keys:", sorted(meta.keys()))
    try:
        df = meta_to_dataframe(meta)
        print("\nDataFrame preview:")
        print(df.head(args.head))
    except Exception as e:
        print("\nDataFrame conversion skipped:", e)
